### ISSUE TITLE
Sending multipart or getting filename in controller?

### ISSUE THREAD

**Issue by nuukular** [antony/grails-ajax-uploader#13]
I am using a custom controller to save the uploaded file to a database. I noticed that the request seems to be of type HttpServletRequest. I don't see any possibility to get the original filename of the file that has been uploaded. However, maybe I am just overlooking something.
If not, is there a convenient way to make the plug-in send the request as multipart-fromdata and include the filename?
Thank you.

**Comment by antony** [comment]
Hi There,

If you inspect the source code, in some instances a MultipartHttpServletRequest is sent (I think this is browsers which use the AJAX functionality), the HttpServletRequest is only used when the iframe solution is used (crap browsers like old versions of IE).

https://github.com/aiten/grails-ajax-uploader/blob/master/grails-app/controllers/uk/co/desirableobjects/ajaxuploader/AjaxUploadController.groovy#L36

Let me know if this helps!

Cheers,
Antony

**Comment by nuukular** [comment]
Thank you for the reply. However, I am not quite sure about the code snippet. To my understanding, this is the handling of the request on the server side. But, if the request is not sent as Multipart, there is little you can do about that on the server side. The client needs to send the mulitpart data. Please correct me, if being wrong.
I just created a new test application to make sure this is not a problem with some other dependencies in my current project. I just added the uploader plug-in to the header of the index.gsp and registered a custom controller:
<uploader:uploader id="yourUploaderId" url="${[controller:'Thumb', action:'upload']}" />

In the controller I print out the received request: 
println 'request: ' + request

This is what is shown on the console: 
request: org.apache.catalina.core.ApplicationHttpRequest@3d1b7f93

I am using Firefox 11 on Ubuntu. 
Any ideas?

**Comment by antony** [comment]
Hi There,

You are correct, the server side determines what type of request it was sent. However the part of code which sends the multipart request is in valum's ajax-uploader project, here:

https://github.com/valums/file-uploader/blob/master/client/fileuploader.js#L1100

Check that the form created by the plugin on your index.gsp is of the correct type (multipart).

I think the ApplicationHttpRequest you are seeing is a wrapper provided by Tomcat, it will probably wrap Grails' own request object which will in turn wrap a MultipartRequest. Try println request.dump() in your controller, or try 'request instanceof Xxx', or having a look to see if you can unwrap the request, and try looking at the network tab in Firebug in Firefox to see if the request headers are set as you expect them to be.

Are you using Grails 2.0.1? I wrote the plugin (and have only tested it so far) using Grails 1.3.7, but the plugin has a lot of users and I haven't had any reports of it not working yet so I don't suppose that is the case.

I'm also using Firefox 11 on Ubuntu, so if I get a chance I'll try to recreate what you're seeing - if you have a sample app you can provide that might help me reproduce it.

Also take a look at valum's original code, as that is what the client-side of my plugin uses, which I don't modify at all - if you can see your problem there then perhaps we can talk to him about getting it fixed.

**Comment by nuukular** [comment]
Thank you for the response. Didn't yet think about firebug to solve that problem - I am more of a java guy, which sadly made me try to avoid the javascript stuff as long as possible. 
It seems that the parameters I have been looking for are sent as query parameters. It is possible to get the filename via
String filename = request.parameterMap.getAt('qqfile')

I am using Grails 2.0.1 by the way. Didn't have any major issues so far, except that I could not get the allowedExtensions option to work. Used the jQuery workaround from one of the other bug reports, which works fine so far.

**Comment by antony** [comment]
Glad you could get your problem resolved! I'm a Java+Groovy guy too, but I've noticed that I'm spending upto 50% of my time in Javascript recently, I think that's the way things are shifting - all rapid feedback and widgets, nobody wants to change pages any more!

Do you have a link to the allowedExtensions bug report? If the issue is in my code I'd like to fix it :)

Cheers,
Antony

**Comment by nuukular** [comment]
Yeah. Javascript is mighty and important. Just didn't have the time yet to get my head into it. But I will have to once I get my controllers and services settled. Grails is a whole new world for me as well... 
I opened another issue about the allowedExtensions thing. 
Thanks for creating such a useful plugin btw.
