### ISSUE TITLE
using GSP expression in params attribute

### ISSUE THREAD

**Issue by nuukular** [antony/grails-ajax-uploader#15]
Probably this is a rather stupid question, but I could not find any way to make this work.
I am passing an Object from my controller to my gsp, which is called versionInstance. I would like to submit the id of the object along with the uploaded file, so I am able to have a reference to which data the uploaded file belongs.
I have tried to configure the uploader this way:

uploader:uploader id="versionUploader" params="${[version:${versionInstance.id.toString()}]}" url="${[controller:'Version', action:'upload']}"

However, I end up with an error stating "Unclosed GSP expression"

If I format the params value this way:

params='${[version:"${versionInstance.id.toString()}"]}'

the upload button just disappears.
the web console in Firefox shows an error and a  warning.
[19:19:16.972] identifier starts immediately after numeric literal
[19:19:17.051] Use of getAttributeNodeNS() is deprecated. Use getAttributeNS() instead.

My id is of type ObjectId, which is specific to the mongodb driver Grails uses. The odd thing is, if I use a different field of the versionInstance, which is a string, it works. I checked the generated source of  both cases:

if I use params='${[version:"${versionInstance.id.toString()}"]}'
the generated source looks like this:

```
        var au_versionUploader = new qq.FileUploader({
        element: document.getElementById('au-versionUploader'),
        action: '/Songreel/version/upload',
        params: {
version: 4f6b7890e4b0a09200977e18
```

},

If I however use a field, which is a String, it looks like this:

```
        var au_versionUploader = new qq.FileUploader({
        element: document.getElementById('au-versionUploader'),
        action: '/Songreel/version/upload',
        params: {
version: 0.1
```

},

The second one works, whereas the first one just makes the upload button disappear. 
I guess the problem is that the quotation marks are missing, which makes the id of an invalid type. If I try to add escaped quotation marks like this
params='${[version:\""${versionInstance.versionString}"\"]}'
I end up with an Unclosed GSP expression error.

Any ideas how to solve this?

**Comment by nuukular** [comment]
In the AjaxUploaderTagLib I temporarily changed the doParamsBlock function.

I replaced the line
paramsBlock << """${entry.key}: ${entry.value instanceof String ? "'${entry.value}'" : entry.value }"""

with:
paramsBlock << """${entry.key}: ${"'${entry.value}'"}"""

As long as the parameters are sent via QueryParameters this actually should not be a problem, but I didn't test this thoroughly though.

**Comment by antony** [comment]
Hi nuukular,

You're double-escaping your string. You need to change this:

```
<uploader:uploader id="versionUploader" params="${[version:${versionInstance.id.toString()}]}" url="${[controller:'Version', action:'upload']}">
```

to:

```
<uploader:uploader id="versionUploader" params="${[version:versionInstance.id]}" url="${[controller:'Version', action:'upload']}">
```

note the:  params="${[version:versionInstance.id]}", because once you're within the ${code block} you can access variables normally.

The paramsBlock line you've changed means that every parameter gets parsed as a String, and double-escaped for some reason. This means that any integer parameters will blow up. Try running the unit tests - you should get some failures with your modified code.

**Comment by antony** [comment]
Oh, if you're having trouble with making it a String, you can still call toString() - just don't have a ${} inside another one - that'll never work - so something like:

```
params="${[version:versionInstance.id.toString()]}",
```

**Comment by nuukular** [comment]
Thank you. Works like a charm.
