### ISSUE TITLE
Using pluging

### ISSUE THREAD

**Issue by jmbarroso** [antony/grails-ajax-uploader#18]
Hello,

I'm not sure how I should use the plugin. Once I upload the file, how I can get it back? . When the file is uploaded, it is stored in the temporary folder of java with a random name, that name is not returned by the ajax call (AjaxUploadController). 

How do I retrieve that file saved in the temporary folder of java if I haven't the name?

Thanks in advanced.

Juan Manuel

**Comment by antony** [comment]
Hi There,

The default controller is provided as an example rather than production ready code. The idea is that you can base your own controller on the code of the example controller, and you will have complete control of the uploaded file.

Cheers,
Antony
