### ISSUE TITLE
Unknown attribute allowedExtentions

### ISSUE THREAD

**Issue by bernji** [antony/grails-ajax-uploader#2]
hello,

i was trying out your uploader plugin but ran into some errors with optional parameters in the uplaoder taglib. here is what I have done:

in the gsp:
<uploader:uploader id="${user.id}" allowedExtentions="'png', 'img', 'gif', 'jpg', 'jpeg'" url="${[controller:'picture', action:'upload']}">

then i got the 
uk.co.desirableobjects.ajaxuploader.exception.UnknownAttributeException: Unknown attribute allowedExtentions

i traced the exception back to the line (in your taglib):
if (!(ALL_ATTRIBUTES.containsKey(attribute.key))) {
                throw new UnknownAttributeException(attribute.key)

although i printed to the console the ALL_ATTRIBUTES attribute:
[id:[], allowedExtensions:[], sizeLimit:[], minSizeLimit:[], debug:[true, false], params:[], messages:[], url:[]]
which looks absolutely right

an the attributes attribute with my optionals:
[id:1, allowedExtentions:'png', 'img', 'gif', 'jpg', 'jpeg', url:[controller:picture, action:upload]]
which looks right as well

i tried a bit around but i could not find the error why it is not working...

**Comment by antony** [comment]
You have specified 'allowedExtentions' instead of 'allowedExtensions' :) i.e, you have a T where there should be an S

In cases like this, I copy paste the asked value into my own code, because it's tiny little typos like this which take so much time to resolve!

Hope this fixes the problem for you!

**Comment by bernji** [comment]
hi, thanks for the support!

owww my fault. that fixed the problem, but i ran into another when specifiing my extenSions :D

<uploader:uploader allowedExtensions="'png','img','gif','jpg'" id="${user.id}" url="${[controller:'picture', action:'uploadProfile']}"></uploader:uploader>

firebug tells me a "invalid object initializer" in this generated js

<script type="text/javascript">

            var au_1 = new qq.FileUploader({
            element: document.getElementById('au-1'),
            action: '/myapp/picture/uploadProfile'
        ,
                    allowedExtensions: 'png','img','gif','jpg'
                ,
onComplete: function(id, fileName, responseJSON) {  alert('file complete!');  },
onComplete: function(id, fileName, responseJSON) {  alert('file complete!');  }
            });
        
</script>


any idea?

**Comment by antony** [comment]
That looks like a real bug! I'll see if I can fix it tonight.

**Comment by antony** [comment]
Hi There!

It's just a bug in grails' wiki, I've escaped the square brackets now, the [ and ] weren't showing up.

basically, use this as your parameter: allowedExtensions="['png','img','gif','jpg']" and it will work.

Sorry about that!
