### ISSUE TITLE
Grails 2.4 compatibility

### ISSUE THREAD

**Issue by wwarlock** [antony/grails-ajax-uploader#22]
Hi, here is the error log.
You are using some deprecated class which now removed from Grails.
Please use 

```
grailsApplication.config
```

or

```
Holders.config
```

Log:

```
  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] ./target/work/plugins/ajax-uploader-1.1/grails-app/controllers/uk/co/desirableobjects/ajaxuploader/AjaxUploadController.groovy: 4: unable to resolve class org.codehaus.groovy.grails.commons.ConfigurationHolder
  [groovyc]  @ line 4, column 1.
  [groovyc]    import static org.codehaus.groovy.grails.commons.ConfigurationHolder.config as Config
  [groovyc]    ^
  [groovyc] 
```

**Comment by antony** [comment]
Hi There,

I've not really tested the plugin against Grails 2.4, but I will fix this
as soon as I have a chance to.

Cheers for the bug report,
Antony

On 3 June 2014 22:48, wwarlock notifications@github.com wrote:

> Hi, here is the error log.
> You are using some deprecated class which now removed from Grails.
> Please use
> 
> grailApplication.config
> 
> or
> 
> Holders.config
> 
> Log:
> 
>   [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
>   [groovyc] ./target/work/plugins/ajax-uploader-1.1/grails-app/controllers/uk/co/desirableobjects/ajaxuploader/AjaxUploadController.groovy: 4: unable to resolve class org.codehaus.groovy.grails.commons.ConfigurationHolder
>   [groovyc]  @ line 4, column 1.
>   [groovyc]    import static org.codehaus.groovy.grails.commons.ConfigurationHolder.config as Config
>   [groovyc]    ^
>   [groovyc]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aiten/grails-ajax-uploader/issues/22.

## 

---

ꜽ . antony jones . http://www.enzy.org

**Comment by wwarlock** [comment]
I can provide to you my code changes.
Will you wish to check these?

**Comment by antony** [comment]
Hi There,

Yep - I'll have a look on github today :)

Thanks!

On 4 June 2014 09:50, wwarlock notifications@github.com wrote:

> I can provide to you my code changes.
> Will you wish to check these?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aiten/grails-ajax-uploader/issues/22#issuecomment-45066532
> .

## 

---

ꜽ . antony jones . http://www.enzy.org

**Comment by JakeRuth** [comment]
I am still seeing this exact same error.  I just tried to use your plugin today (08/10/2014), is this change fix committed to the published plugin?  I will make my changes locally however it would be nice if it was fixed, thanks!

**Comment by pbujko** [comment]
guys, is fixed version available for use?
it can not be found when I try in BuildConfig:

```
plugins {
```

...
        compile ":ajax-uploader:1.3"
}

**Comment by antony** [comment]
Hi guys

I realise I'm being really slow on publishing this.

I'll try to publish it tomorrow.

Sorry about the delay,
Antony

—

**Comment by pbujko** [comment]
would be great!

**Comment by antony** [comment]
Hi There,

This is now done - athough I can't update the portal, version 1.3 is there.

**Comment by pbujko** [comment]
UPDATE:
after installing v 1.3 I am seeing:

2014-09-09 16:14:21,766 ERROR org.grails.plugin.resource.ResourceMeta - While processing /bundle-bundle_fileuploader_head.css, /css/uploader.css, a resource was required but not found: /css/loading.gif

**Comment by pbujko** [comment]
Hey, I can make fix for one above - it is in resources configuration. interested in pull req?

**Comment by antony** [comment]
Always interested in pull requests! Apologies it took me a while to see this.
