### ISSUE TITLE
strange behaviour with IE

### ISSUE THREAD

**Issue by bernji** [antony/grails-ajax-uploader#4]
hello,

i used you uploader with Internet Explorer 8.
after i choose a file the filename and the cancel link appear as expected.
Then normally the progress would appear. but instead of that a download window pops up and asks if i want to save a file. the filename is the same as my action (in my case the file "uploader" without any extention). The content of that file is the response of the json request. (in my case {"success":false} ) as it would be in your example controller

have you tried your uploader with any IE?

**Comment by antony** [comment]
Hi There,

What version are you using? There was a problem like that in Internet Explorer with the previous version, but the latest version has a fix for that. It seems that IE can't handle JSON properly (or, handle anything properly in fact), so the {success: false} is now rendered as text.

**Comment by bernji** [comment]
hi aiten,

normally i am using firefox of cause. i just want the uploader working if someone else is not using firefox (which many people do)
i used the Internet Explorer which was installed in my windows 7 pc. That Version 8.9.7600.16385
But i don't want to ask to install any fixes to use the uploader...
is there any way to handle this? how are i.e. facebook doing it? are they using ajax?

**Comment by bernji** [comment]
hi aiten,

i played around with the internet explorer and the async requests with JSON i use by myself.
I used jquery to send the JSON requests on client side and (of cause) grails so send a JSON response.

this is my code:

``` javascript
function setUserdata(savebutton, type, value) {
            $.post('${g.createLink(controller:'async', action:'setUserdata')}',
                { type: type, value:value},
            function(data) {
                    console.debug(data)
            });     
}     
```

data is the respons i get from my action.
it appears that the response is handled correctly by both - internet explorer and Firefox.
In other words internet exporer supports and handles JSON.

If i can somehow help you with getting your uploaded to work with Internet exporer let me know! i think the uploader is great!

**Comment by antony** [comment]
Hey,

I've not experienced this with the current version at all - Fortunately I don't own a copy of windows so I don't test on IE often!

If you see a problem though and you fancy forking the plugin and sending me a pull request that is perfect - my only requirement is that you have a unit test/functional test for the bug you are fixing (might be tricky since it's IE only).

I do have access to a Windows 7 machine at work, so if you do a 'grails bug-report' and send me the zip file it makes, I will try your application out to see it for myself.

Thanks for your help :)

**Comment by antony** [comment]
Oh - also when I said what version are you using - I meant plugin version - do you know what version of my plugin you are using?

**Comment by bernji** [comment]
i am not very much into javascript and the client side of a web applikation. I am more into backend/grails...
but i will try to investigate what the problem with the ie is.

ohh sure. i use plugins.ajax-uploader=0.3

**Comment by bernji** [comment]
hey,

i googled for a bit and found this article:
http://devcentral.f5.com/weblogs/macvittie/archive/2008/06/26/3397.aspx
there are 3 ways described to fix this problem. i am not sure which suites to your implementation but it looks like its a known bug.
is this helping?

**Comment by bernji** [comment]
i figured it out now! 2 issues caused the problem:
1. the received file had the size of 0
2. the JSOn response was not interpreted correctly (a download with the response poped out)

fix for 1:
when uploading with IE the params.qqfile is not the filename (as it is in FF or any other browser) it is a org.springframework.web.multipart.commons.CommonsMultipartFile
in the upload controller you need to fork for IE and not IE:

```
    if (params.qqfile instanceof org.springframework.web.multipart.commons.CommonsMultipartFile){
        log.debug "Multipart"
        content = params.qqfile.getBytes()
        originalFilename = params.qqfile.originalFilename
    }
    else{
        log.debug "normal"
        content = request.inputStream.getBytes()
        originalFilename = params.qqfile
    }
```

fix for 2:
use:
render "{success: true}"
instead of
render ([success:true] as JSON)

**Comment by antony** [comment]
Hi Berjni, 

All your problems are caused because you're using the wrong plugin version! I released 0.4 to fix these exact issues, a few months ago.

Upgrade to 0.4 and you will have no further issues :)

Cheers,
Antony

**Comment by bernji** [comment]
well... i have version 0.4 as I told you 2 posts ago....

Am 13/09/2011 14:17, schrieb aiten:

> Hi Berjni,
> 
> All your problems are caused because you're using the wrong plugin version! I released 0.4 to fix these exact issues, a few months ago.
> 
> Upgrade to 0.4 and you will have no further issues :)
> 
> Cheers,
> Antony

**Comment by antony** [comment]
Nope, you said you had 0.3:

> > ohh sure. i use plugins.ajax-uploader=0.3

**Comment by bernji** [comment]
ohhh okay... sorry...

**Comment by rvargas** [comment]
I have 0.4, but IE doesn't get any response. Spinner shows at infinity.

I have this:

return render(text: [success:true, pathFile:pathFile,imgName:imgName] as JSON, contentType:'text/json')

Chrome and firefox works well.

**Comment by antony** [comment]
Hi.

If you check in the upload controller provided with version 0.4 of the plugin, you'll see that the contentType for IE needs to be 'text/plain', because IE is a crap browser which can't handle JSON properly.

Cheers,
Antony

**Comment by rvargas** [comment]
Hi

I changed 

return render(text: [success:true, pathFile:pathFile,imgName:imgName] as JSON, contentType:'text/json')

to

return render(text: [success:true,pathFile:pathFile,imgName:imgName] as JSON, contentType:'text/plain')

and the upload finish, but the response is "failure".

Any ideas?

**Comment by bernji** [comment]
try to render the JSON manualy. that made it run for me:
render "{success: true}"

**Comment by antony** [comment]
What browser are you using rvargas?

It's working fine for me on IE

**Comment by antony** [comment]
Also maybe try putting contentType as your FIRST argument to render, the render method is a bit odd.

**Comment by NatoCrisis** [comment]
I've been struggling with similar problems - using contentType:'text/html' worked for me.
