### ISSUE TITLE
change name of upload button

### ISSUE THREAD

**Issue by bernji** [antony/grails-ajax-uploader#5]
hey,

is there a way to change the name "upload a file" into something like "upload a picture"?

cheers

**Comment by antony** [comment]
Hey,

As of now, there is not, but I think this would be a good feature to have. I'll implement it for the next release! Unfortunately, 'upload a file' is built-in to the javascript library I depend on, so I'll have to start hacking around in there.

Please raise an improvement in the grails jira against the plugin, and I'll add the feature!

Cheers,
Antony

**Comment by bernji** [comment]
hey antony,

could you raise the improvment? you will know better then me on what your plugin depends on and how to formulate the improvement.
I would love to see that feature in your next release!

cheers,
bernhard

**Comment by antony** [comment]
Hi bernji,

No, I'll do the work if you raise an improvement request - I don't have time to do everything!

**Comment by bernji** [comment]
hi antony,

this is the sollution to change the name with moottools. you may wanna change that because your plugin doesn't depend on any library (which is perfect):

$$('.qq-upload-drop-area span').set('html', 'Some text for drag and drop'); 
    var input = $$('.qq-upload-button input')[0]; 
    var uploadButton = $$('.qq-upload-button')[0] 
    uploadButton.set('text', 'Some button text'); 
    input.inject(uploadButton);

**Comment by antony** [comment]
Hi Bernji,

That sounds cool - there are a few features which I'd like to see in the ajax uploader, I'll see if Andrew Valums wants any of them and then hopefully we can push this change upstream.

Cheers,
Antony

**Comment by bernji** [comment]
that would be really cool!
