### ISSUE TITLE
Upgrade to Grails 2.0

### ISSUE THREAD

**Issue by stewsters** [antony/grails-ajax-uploader#7]
What do I need to do to get this to work in 2.0?

I noticed that when I upgraded from 1.3.7 it stopped working and threw errors relating to the new resource tags:

Message: Error applying layout : admin/default
   Line | Method
->> 886 | runTask in \grails-app\views\layouts\admin\default.gsp

---

|   908 | run     in     ''
^   662 | run . . in     ''

Caused by GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:applyLayout>: Error executing tag <r:layoutResources>: No module found with name [fileuploader]
->>  11 | runTask in \grails-app\views\layouts\admin\default.gsp

---

Caused by GrailsTagException: Error executing tag <g:applyLayout>: Error executing tag <r:layoutResources>: No module found with name [fileuploader]
->>  24 | run     in C:/code/WebsiteRedesign/grails-app/views/layouts/admin/default.gsp

---

Caused by GrailsTagException: Error executing tag <r:layoutResources>: No module found with name [fileuploader]
->>  30 | doCall  in C:/code/WebsiteRedesign/grails-app/views/layouts/admin/base.gsp

---

Caused by IllegalArgumentException: No module found with name [fileuploader]
->> 1098 | getAllModuleNamesRequired in org.grails.plugin.resource.ResourceProcessor

---

|   375 | doCall  in org.grails.plugin.resource.ResourceTagLib$_closure6
|    30 | doCall  in C__code_WebsiteRedesign_grails_app_views_layouts_admin_base_gsp$_run_closure1
|    32 | run     in C__code_WebsiteRedesign_grails_app_views_layouts_admin_base_gsp
|    24 | run . . in C__code_WebsiteRedesign_grails_app_views_layouts_admin_default_gsp
|   886 | runTask in java.util.concurrent.ThreadPoolExecutor$Worker
|   908 | run . . in     ''
^   662 | run     in java.lang.Thread

**Comment by antony** [comment]
Hi,

Yeah - it looks like the plugin is not resources compliant yet.

I've not yet had the chance to upgrade these plugins to Grails 2.0. I'll hopefully get some time over Christmas to do this.

Cheers,
Antony

**Comment by antony** [comment]
Hi There,

Problem solved - let me know if you have any more issues. Please upgrade to version 1.0 and see the updated documentation for the resources plugin http://www.grails.org/plugin/ajax-uploader

Thanks for the report!

Antony

**Comment by stewsters** [comment]
Thanks!

On Wed, Dec 28, 2011 at 7:56 AM, Antony Jones
reply@reply.github.com
wrote:
